import Navbar from './navbar';
import Footer from './footer';
import { NextConfig } from "next";
import Head from "next/head";

export default function Layout({ children }: NextConfig) {
    return (
        <>
            <Head>
                <title>rookie</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Navbar />
                {children}
                <Footer />
            </main>
        </>
    )
}